### ISSUE TITLE
VMP and betterfpsdistance conflict

### ISSUE THREAD

**Issue by AlexanderwithaA** [RelativityMC/VMP-fabric#53] opened 2023-12-27 07:37 UTC
**Describe the bug**
vmp causes betterfpsdistance to not work correctly, betterfpsdistance changes minecraft to render in a circle since fog covers the corners, having vmp stops that.

**To Reproduce**
1. install the fabric versions of vmp and betterfpsdistance along with necessary dependencies.
2. create a new world and fly up high to so you can see where the corners of the rendered area are/should be. (a mod to disable fog might be useful to see this)

**Expected behavior**
the rendered area is circular.

**Screenshots**
betterfpsdistance only
![2023-12-26_22 58 47](https://github.com/RelativityMC/VMP-fabric/assets/101488091/084f4334-cf67-4333-b0bd-c9ee67366f65)
both mods
![2023-12-26_23 07 50](https://github.com/RelativityMC/VMP-fabric/assets/101488091/116e8e25-c5c7-4bfd-958a-78fe08d3be7e)

**Runtime info (please complete the following information):**
 - OS: windows 11
 - Minecraft version: 1.20.4
 - Mod version: vmp-fabric-mc1.20.4-0.2.0+beta.7.135-all
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**
https://mclo.gs/ZZ3bMKT

**Other mods**
https://pastebin.com/hstjqDpU

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
I'm using vulkanmod instead of sodium

**Comment by ishland** [comment] 2023-12-27 14:15
Working as intended. 

VMP replaces the chunk sending to make it cost less to track sent chunks, and the square chunk sending behavior is intentional. 

You have already disabled the fog, chunks behind the fog should still render.

**Comment by ishland** [comment] 2023-12-27 14:25
Oops didn't mean to close this

**Comment by AlexanderwithaA** [comment] 2023-12-28 10:16
I was just looking at this again because vmp was making my performance worse, mojang made chunk rendering cylindrical in snapshot 21w37a, could vmp reflect this change?
https://minecraft.wiki/w/Java_Edition_21w37a#General_2

**Comment by ishland** [comment] 2024-01-01 05:50
> I was just looking at this again because vmp was making my performance worse, mojang made chunk rendering cylindrical in snapshot 21w37a, could vmp reflect this change? https://minecraft.wiki/w/Java_Edition_21w37a#General_2

Chunk rendering should already be cylindrical if both fog and fog occlusion is enabled. 
And as I mentioned above, the revert to square chunk sending behavior is intentional in VMP. Chunk loading in vanilla is also never cylindrical even after 21w37a.

**Comment by AlexanderwithaA** [comment] 2024-01-02 00:19
I'm talking about rendering not loading, what I'm concerned about is that the rendering with vmp is square while in vanilla it's cylindrical. Top image is 1.18.2 vanilla, middle is 1.18.2 with vmp, and bottom is 1.20.2 vanilla. So is it intentional that vmp renders chunks in a square?

![2024-01-01_16 15 26](https://github.com/RelativityMC/VMP-fabric/assets/101488091/b4a986ae-000a-44fe-ad69-79425de9216e)
![2024-01-01_16 06 05](https://github.com/RelativityMC/VMP-fabric/assets/101488091/f8fadac9-3a37-45b2-accc-434ef302ca0e)
![2024-01-01_16 16 10](https://github.com/RelativityMC/VMP-fabric/assets/101488091/34a802a1-88d6-4781-abc9-fe63d552aee8)

**Comment by ishland** [comment] 2024-01-02 04:22
It is intentional.

There are a few reasons for this:
- Quite some optimization in vmp assumes that square render distance is used. 
- Making server-sided tracking of square render distance is cheaper than the cylindrical one.
- It is the rendering optimization mod's job to cull chunks behind the fog.

**Closed as not planned** 2024-10-28 07:07 UTC
Labels: bug, question
