### ISSUE TITLE
C2ME + VMP = not loading chunks

### ISSUE THREAD

**Issue by mllightitup** [RelativityMC/VMP-fabric#16] opened 2022-06-14 14:32 UTC
**Describe the bug**
If both mods are installed: c2me and vmp then only about 10 chunks are loaded (visually). This happens only if in config file c2me.toml turn off [threadedWorldGen]. From this follows another problem, if I have [threadedWorldGen] enabled then the chunks are generated many times slower than in vanilla and constantly lags and sometimes hangs completely for a significant period of time.
The amount of allocated memory has no effect on this in my case. I tried with both 6GB and 12GB. I also tried different GCs (zgc, shenandoah, g1gc) but none of these critically affect the situation

**To Reproduce**
1. install c2me and vmp
2. disable [threadedWorldGen]
3. set draw distance to 32 chunks for example
4. create new world 

**Expected behavior**
To the vmp-related bug: Chunks should load normally
To the c2me related problem: Most likely, the use of these two mods implies performance and speed of loading and generation of chunks more than in vanilla and certainly not worse

**Screenshots**

![image](https://user-images.githubusercontent.com/43480503/173604261-8ecdb540-29c6-4350-b247-96ef76966aa4.png)

**Runtime info (please complete the following information):**
 - OS: win 10 pro 21h2
 - Minecraft version: 1.19
 - Mod version: 0.2.0+beta.4.0
 - CPU: i5 9600k
 - GPU: 1060 3gb
 - RAM: 16gb ddr4 (6/12 allocated)
 - JDK: 17 (Temurin/graalvm)

**Crash reports / logs**
no crash

**Other mods**
c2me

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

Since the bug is related to two mods, maybe I should also write to c2me/issues?

**Comment by toinouH** [comment] 2022-06-14 18:28
@mllightitup You don't need to open another issue.

**Comment by mllightitup** [comment] 2022-06-14 19:47
> @mllightitup You don't need to open another issue.

ok

**Comment by ishland** [comment] 2022-06-18 12:38
I can't reproduce this error with `threadedWorldGen` disabled. Can you try again with current latest dev builds again?

**Comment by mllightitup** [comment] 2022-06-18 14:53
This bug has been fixed with the latest dev versions of vmp+c2me. By the way, [threadedWorldGen] is now turned off by default in the c2me config. 
![image](https://user-images.githubusercontent.com/43480503/174443853-743f907b-0f12-45ce-94cf-02e64a2efac1.png)


> I can't reproduce this error with `threadedWorldGen` disabled. Can you try again with current latest dev builds again?

**Comment by ishland** [comment] 2022-06-18 14:56
> This bug has been fixed with the latest dev versions of vmp+c2me. 

Then this issue will be closing as resolved. 

> By the way, [threadedWorldGen] is now turned off by default in the c2me config. ![image](https://user-images.githubusercontent.com/43480503/174443853-743f907b-0f12-45ce-94cf-02e64a2efac1.png)

This is because I forgot to turn that off automatically for users that have a relatively lower-end machines to avoid possible performance issues.

**Closed as completed by ishland** 2022-06-18 14:56 UTC
Labels: bug, question
